buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Modern Android Gradle Plugin version jo Gradle 8.5 ke sath perfectly compatible hai
        classpath 'com.android.tools.build:gradle:8.1.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
