# Project-wide Gradle settings.

# IDE (Android Studio / GitHub Actions) ke liye JVM arguments aur memory allocation
org.jvm.hotspot.compiler.UseSSE=4
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX ko enable karna modern support libraries ke liye
android.useAndroidX=true

# Non-ASCII characters ya special strings ko avoid karne ke liye
android.enableJetifier=true
